### ISSUE TITLE
Fails to build on arm64

### ISSUE THREAD

**Issue by popey** [snapcrafters/obs-studio#1]
[libfdk-aac-dev](https://packages.ubuntu.com/search?keywords=libfdk-aac-dev) isn't available in arm64 on xenial. 

So it fails to [build](https://launchpadlibrarian.net/370023289/buildlog_snap_ubuntu_xenial_arm64_4c109af8362ee005d363700d9b864814-xenial_BUILDING.txt.gz)

```
Downloading parts list                                                         
Downloading parts list                                                         
Downloading parts list                                                         
Downloading parts list                                                         
Could not find a required package in 'build-packages': libfdk-aac-dev
Build failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 269, in run
    self.pull()
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 221, in pull
    env=env)
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 103, in run_build_command
    return self.backend.run(args, cwd=cwd, env=full_env, **kwargs)
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/lxd.py", line 456, in run
    subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['lxc', 'exec', 'lp-xenial-arm64', '--env', 'LANG=C.UTF-8', '--env', 'SHELL=/bin/sh', '--env', 'SNAPCRAFT_LOCAL_SOURCES=1', '--env', 'SNAPCRAFT_SETUP_CORE=1', '--env', 'SNAPCRAFT_BUILD_INFO=1', '--env', 'SNAPCRAFT_IMAGE_INFO={"build_url": 
```

**Comment by flexiondotorg** [comment]
`obs-studio` snap is now builkd against `core18` and `libfdk-aac-dev` is available for arm64.
