### ISSUE TITLE
Cannot load any Python scripts.

### ISSUE THREAD

**Issue by ymauray** [snapcrafters/obs-studio#64]
Hi !

Using the snap, I am unable to load any python script from the `Tools > Scripts` dialog. 

Even this "script" - a single line of comment -  won't load :
```python
# OBS-Studio python scripts
``` 

I get this in the script logs : 

```text
[helloworld.py] Traceback (most recent call last):
[helloworld.py]   File "<frozen importlib._bootstrap_external>", line 1096, in _path_importer_cache
[helloworld.py] KeyError: '/home/yannick/Téléchargements/'
[helloworld.py] 
[helloworld.py] During handling of the above exception, another exception occurred:
[helloworld.py] 
[helloworld.py] Traceback (most recent call last):
[helloworld.py]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[helloworld.py]   File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
[helloworld.py]   File "<frozen importlib._bootstrap>", line 894, in _find_spec
[helloworld.py]   File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
[helloworld.py]   File "<frozen importlib._bootstrap_external>", line 1126, in _get_spec
[helloworld.py]   File "<frozen importlib._bootstrap_external>", line 1098, in _path_importer_cache
[helloworld.py]   File "<frozen importlib._bootstrap_external>", line 1074, in _path_hooks
[helloworld.py] UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 15: ordinal not in range(128)
```

That exact same script - if it can be called like that - loads perfectly using the deb.

Thanks !

**Comment by popey** [comment]
Heya, thanks for the report.
Does it work from a folder which doesn't have any 'weird' characters in it, rather than `Téléchargements`?

**Comment by ymauray** [comment]
Hum... this is embarrassing.
I can't reproduce this today. I loads just fine, even from a directory with accents, which by the way are __not__ weird characters :-).
Let's close this issue, then. If I ever figure out what I did last week, I'll open a new one - after a few days ^^
